"""empty message

Revision ID: 1612b9430fc6
Revises: 2f20bdd1d28d
Create Date: 2014-09-16 11:28:07.847327

"""

# revision identifiers, used by Alembic.
revision = '1612b9430fc6'
down_revision = '2f20bdd1d28d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('catalog_category', sa.Column('entity_type_id', sa.Integer(), nullable=True))
    op.add_column('catalog_category', sa.Column('lft', sa.Integer(), nullable=True))
    op.add_column('catalog_category', sa.Column('rgt', sa.Integer(), nullable=True))
    op.add_column('catalog_category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('catalog_product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('catalog_product', sa.Column('entity_type_id', sa.Integer(), nullable=True))
    op.add_column('catalog_product', sa.Column('sku', sa.String(length=64), nullable=True))
    op.add_column('catalog_product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('eav_attribute', sa.Column('attribute_code', sa.String(length=64), nullable=True))
    op.add_column('eav_attribute', sa.Column('backend_type', sa.String(length=64), nullable=True))
    op.add_column('eav_attribute', sa.Column('entity_type_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eav_attribute', 'entity_type_id')
    op.drop_column('eav_attribute', 'backend_type')
    op.drop_column('eav_attribute', 'attribute_code')
    op.drop_column('catalog_product', 'updated_at')
    op.drop_column('catalog_product', 'sku')
    op.drop_column('catalog_product', 'entity_type_id')
    op.drop_column('catalog_product', 'created_at')
    op.drop_column('catalog_category', 'updated_at')
    op.drop_column('catalog_category', 'rgt')
    op.drop_column('catalog_category', 'lft')
    op.drop_column('catalog_category', 'entity_type_id')
    op.drop_column('catalog_category', 'created_at')
    ### end Alembic commands ###
