"""empty message

Revision ID: 275b2dc55cba
Revises: None
Create Date: 2014-09-02 15:38:32.257801

"""

# revision identifiers, used by Alembic.
revision = '275b2dc55cba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
