"""empty message

Revision ID: 2f20bdd1d28d
Revises: None
Create Date: 2014-09-15 18:32:19.482956

"""

# revision identifiers, used by Alembic.
revision = '2f20bdd1d28d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
