"""empty message

Revision ID: 4bd84a4148c6
Revises: f2c94c068f0
Create Date: 2014-10-14 17:40:27.082900

"""

# revision identifiers, used by Alembic.
revision = '4bd84a4148c6'
down_revision = 'f2c94c068f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
