"""empty message

Revision ID: 5717a31c1233
Revises: 7381a9ac29b
Create Date: 2014-09-16 16:14:44.716606

"""

# revision identifiers, used by Alembic.
revision = '5717a31c1233'
down_revision = '7381a9ac29b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_address', sa.Column('address_type', sa.Enum('shipping', 'billing'), nullable=True))
    op.add_column('customer_address', sa.Column('external_address_id', sa.Integer(), nullable=True))
    op.drop_column('customer_address', 'method_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_address', sa.Column('method_type', mysql.ENUM(u'shipping', u'billing'), nullable=True))
    op.drop_column('customer_address', 'external_address_id')
    op.drop_column('customer_address', 'address_type')
    ### end Alembic commands ###
