"""empty message

Revision ID: 7381a9ac29b
Revises: 1612b9430fc6
Create Date: 2014-09-16 15:17:49.964230

"""

# revision identifiers, used by Alembic.
revision = '7381a9ac29b'
down_revision = '1612b9430fc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('increment_id', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'increment_id')
    ### end Alembic commands ###
