"""empty message

Revision ID: f2c94c068f0
Revises: None
Create Date: 2014-10-14 16:46:24.686003

"""

# revision identifiers, used by Alembic.
revision = 'f2c94c068f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
